stages:
        - compile
        - test
        - deploy


assemble:
        stage: compile
        script: ./gradlew assemble

check:
        stage: test
        dependencies:
                - assemble
        script: ./gradlew check -i
        artifacts:
                paths:
                        - build/reports/tests/test/


pages_success:
        stage: deploy
        script:
                - mv build/reports/tests/test/ public/
        artifacts:
                paths:
                        - public
                expire_in: 30 days
        only:
                - master
        when: on_success

pages_failure:
        stage: deploy
        script:
                - ./gradlew check -i -PignoreTestFailures=true
                - mv build/reports/tests/test/ public/
        artifacts:
                 paths:
                        - public
                 expire_in: 30 days
        only:
                - master
        when: on_failure