stages:
        - compile
        - test
        - retest
        - deploy


assemble:
        stage: compile
        script: ./gradlew assemble

check:
        stage: test
        dependencies:
                - assemble
        script: ./gradlew check -i
        artifacts:
                paths:
                        - build/reports/tests/test/

recheck_failure:
        stage: retest
        script:
                - ./gradlew check -i -PignoreTestFailures=true
        artifacts:
                paths:
                        - build/reports/tests/test/
        when: on_failure

pages_success:
        stage: deploy
        script:
                - mv build/reports/tests/test/ public/
        dependencies:
                - check
        artifacts:
                paths:
                        - public
                expire_in: 30 days
        only:
                - master
        when: on_success


pages_failure:
        stage: deploy
        script:
                - mv build/reports/tests/test/ public/
        dependencies:
                - recheck_failure
        artifacts:
                 paths:
                        - public
                 expire_in: 30 days
        only:
                - master
        when: on_failure