stages:
        - compile
        - test
        - deploy


assemble:
        stage: compile
        script: ./gradlew assemble

check:
        stage: test
        dependencies:
                - assemble
        script: ./gradlew check -i
        artifacts:
                paths:
                        - build/reports/tests/test/


pages:
        stage: deploy
        dependencies:
                - check
        script:
                - mv build/reports/tests/test/ public/
        artifacts:
                paths:
                        - public
                expire_in: 30 days
        only:
                - master

