stages:
        - test
        - deploy


check:
        stage: test
        script: ./gradlew clean check -i
        artifacts:
                paths:
                        - build/reports/tests/test/
                when: always


pages:
        stage: deploy
        dependencies:
                - check
        script:
                - mv build/reports/tests/test/ public/
        artifacts:
                paths:
                        - public
                expire_in: 30 days
        only:
                - master
        when: always

