#!/usr/bin/ruby
# comand line script that sends an HTTPS request to the WACC compiler web interface and interprets the JSON response

require "rest-client"
require "json"
require "optparse"


ARGV << "-h" if ARGV.empty?

$options = {}
$opts = []
$opts << "-a" 
$opts << "-x" 

# set up empty array of file_paths to process
files = []
file_path = ARGV[0]
stdin = ARGV[1]

  RestClient.post("https://teaching.doc.ic.ac.uk/wacc_compiler/run.cgi", 
                    :stdin => stdin,
                    :options => $opts,
                    :testfile => File.new(file_path)
                   ) do |response|
    json = JSON.load(response)
    puts json['upload']
    puts "-- Compiler Output:"
    puts json['compiler_out']
    puts ""

  
end
