#!/usr/bin/ruby

require "rest-client"                                                                             
require "json"                                                                                    


file_path = ARGV[0]
stdin = ARGV[1]

RestClient.post("https://teaching.doc.ic.ac.uk/wacc_compiler/run.cgi",
                 :stdin => stdin,
                 :testfile => File.new(file_path)
               ) do |response|
json = JSON.load(response)
puts json['emulator_out']


end
